const luluCurrencies = [
  { code: "INR", name: "INDIAN RUPEE" },
  { code: "PKR", name: "PAKISTANI RUPEE" },
  { code: "BDT", name: "BANGLADESHI TAKA" },
  { code: "PHP", name: "PHILIPPINE PESO" },
  { code: "EGP", name: "EGYPTIAN POUND" },
  { code: "KES", name: "KENYAN SHILLING" },
  { code: "MAD", name: "MOROCCAN DIRHAM" },
  { code: "MUR", name: "MAURITIUS RUPEE" },
  { code: "CHF", name: "SWISS FRANC" },
  { code: "VND", name: "VIETNAMESE DONG" },
  { code: "BRL", name: "BRAZILIAN REAL" },
  { code: "OMR", name: "OMANI RIYAL" },
  { code: "RUB", name: "RUSSIAN FEDERATION ROUBLE" },
  { code: "NZD", name: "NEW ZEALAND DOLLAR" },
  { code: "SEK", name: "SWEDISH KRONA" },
  { code: "AZN", name: "AZERBAIJAN MANAT(AZN)" },
  { code: "AUD", name: "AUSTRALIAN DOLLAR" },
  { code: "RSD", name: "SERBIAN DINAR" },
  { code: "BAM", name: "CONVERTIBLE MARK" },
  { code: "IDR", name: "INDONESIA RUPIAH" },
  { code: "SCP", name: "SCOTLAND POUND" },
  { code: "UGX", name: "UGANDA SHILLING" },
  { code: "GBP", name: "BRITISH POUND" },
  { code: "JPY", name: "JAPANESE YEN" },
  { code: "NOK", name: "NORWEGIAN KRONE" },
  { code: "CAD", name: "CANADIAN DOLLAR" },
  { code: "USD", name: "US DOLLAR" },
  { code: "EUR", name: "EURO" },
  { code: "SAR", name: "SAUDI RIYAL" },
  { code: "ZAR", name: "SOUTH AFRICAN RAND" },
  { code: "LBP", name: "LEBANESE POUND" },
  { code: "IEP", name: "IRISH POUND" },
  { code: "TZS", name: "TANZANIAN SHILLING" },
  { code: "NGN", name: "NAIRA" },
  { code: "PLN", name: "POLISH ZLOTY" },
  { code: "KWD", name: "KUWAITI DINAR" },
  { code: "CNY", name: "CHINESE RENMINBI YUAN" },
  { code: "GEL", name: "GEORGIAN LARI" },
  { code: "CZK", name: "CZECH KORUNA" },
  { code: "NPR", name: "NEPALESE RUPEE" },
  { code: "LKR", name: "SRI LANKAN RUPEE" },
  { code: "MYR", name: "MALAYSIAN RINGGIT" },
  { code: "DKK", name: "DANISH KRONE" },
  { code: "SCR", name: "SEYCHELLES RUPEE" },
  { code: "BHD", name: "BAHRAINI DINAR" },
  { code: "GHS", name: "GHANAIAN CEDI" },
  { code: "BND", name: "BRUNEI DOLLAR" },
  { code: "TND", name: "TUNISIAN DINAR" },
  { code: "KRW", name: "SOUTH KOREAN WON" },
  { code: "SGD", name: "SINGAPORE DOLLAR" },
  { code: "TWD", name: "TAIWAN DOLLAR" },
  { code: "HKD", name: "HONG KONG DOLLAR" },
  { code: "JOD", name: "JORDANIAN DINAR" },
  { code: "IQD", name: "IRAQI DINAR" },
  { code: "TRL", name: "TURKISH LIRA" },
  { code: "QAR", name: "QATARI RIYAL" },
  { code: "THB", name: "THAILAND BAHT" },
];

const fardanCurrencies = [
  { code: "AUD", name: "AUSTRALIAN DOLLAR" },
  { code: "BDT", name: "BANGLADESHI TAKA" },
  { code: "BHD", name: "BAHRAINI DINAR" },
  { code: "CAD", name: "CANADIAN DOLLAR" },
  { code: "CHF", name: "SWISS FRANC" },
  { code: "CNY", name: "CHINESE RENMINBI YUAN" },
  { code: "CYP", name: "CYPRIOT POUND" },
  { code: "DKK", name: "DANISH KRONE" },
  { code: "EGP", name: "EGYPTIAN POUND" },
  { code: "EUR", name: "EURO" },
  { code: "GBP", name: "BRITISH POUND" },
  { code: "HKD", name: "HONG KONG DOLLAR" },
  { code: "IDR", name: "INDONESIA RUPIAH" },
  { code: "INR", name: "INDIAN RUPEE" },
  { code: "JOD", name: "JORDANIAN DINAR" },
  { code: "JPY", name: "JAPANESE YEN" },
  { code: "KWD", name: "KUWAITI DINAR" },
  { code: "LBP", name: "LEBANESE POUND" },
  { code: "LKR", name: "SRI LANKAN RUPEE" },
  { code: "MAD", name: "MOROCCAN DIRHAM" },
  { code: "MYR", name: "MALAYSIAN RINGGIT" },
  { code: "NOK", name: "NORWEGIAN KRONE" },
  { code: "NPR", name: "NEPALESE RUPEE" },
  { code: "NZD", name: "NEW ZEALAND DOLLAR" },
  { code: "OMR", name: "OMANI RIYAL" },
  { code: "PHP", name: "PHILIPPINE PESO" },
  { code: "PKR", name: "PAKISTANI RUPEE" },
  { code: "QAR", name: "QATARI RIYAL" },
  { code: "SAR", name: "SAUDI RIYAL" },
  { code: "SEK", name: "SWEDISH KRONA" },
  { code: "SGD", name: "SINGAPORE DOLLAR" },
  { code: "SYP", name: "SYRIAN POUND" },
  { code: "THB", name: "THAILAND BAHT" },
  { code: "TND", name: "TUNISIAN DINAR" },
  { code: "TRY", name: "TURKISH LIRA" },
  { code: "USD", name: "US DOLLAR" },
  { code: "YER", name: "YEMENI RIAL" },
  { code: "ZAR", name: "SOUTH AFRICAN RAND" },
];

const ansariCurrencies = [
  { code: "INR", name: "INDIAN RUPEE" },
  { code: "PKR", name: "PAKISTANI RUPEE" },
  { code: "BDT", name: "BANGLADESHI TAKA" },
  { code: "PHP", name: "PHILIPPINE PESO" },
  { code: "EGP", name: "EGYPTIAN POUND" },
  { code: "KES", name: "KENYAN SHILLING" },
  { code: "MAD", name: "MOROCCAN DIRHAM" },
  { code: "MUR", name: "MAURITIUS RUPEE" },
  { code: "CHF", name: "SWISS FRANC" },
  { code: "VND", name: "VIETNAMESE DONG" },
  { code: "BRL", name: "BRAZILIAN REAL" },
  { code: "OMR", name: "OMANI RIYAL" },
  { code: "RUB", name: "RUSSIAN FEDERATION ROUBLE" },
  { code: "NZD", name: "NEW ZEALAND DOLLAR" },
  { code: "SEK", name: "SWEDISH KRONA" },
  { code: "AZN", name: "AZERBAIJAN MANAT(AZN)" },
  { code: "AUD", name: "AUSTRALIAN DOLLAR" },
  { code: "RSD", name: "SERBIAN DINAR" },
  { code: "BAM", name: "CONVERTIBLE MARK" },
  { code: "IDR", name: "INDONESIA RUPIAH" },
  { code: "SCP", name: "SCOTLAND POUND" },
  { code: "UGX", name: "UGANDA SHILLING" },
  { code: "GBP", name: "BRITISH POUND" },
  { code: "JPY", name: "JAPANESE YEN" },
  { code: "NOK", name: "NORWEGIAN KRONE" },
  { code: "CAD", name: "CANADIAN DOLLAR" },
  { code: "USD", name: "US DOLLAR" },
  { code: "EUR", name: "EURO" },
  { code: "SAR", name: "SAUDI RIYAL" },
  { code: "ZAR", name: "SOUTH AFRICAN RAND" },
  { code: "LBP", name: "LEBANESE POUND" },
  { code: "IEP", name: "IRISH POUND" },
  { code: "TZS", name: "TANZANIAN SHILLING" },
  { code: "NGN", name: "NAIRA" },
  { code: "PLN", name: "POLISH ZLOTY" },
  { code: "KWD", name: "KUWAITI DINAR" },
  { code: "CNY", name: "CHINESE RENMINBI YUAN" },
  { code: "GEL", name: "GEORGIAN LARI" },
  { code: "CZK", name: "CZECH KORUNA" },
  { code: "NPR", name: "NEPALESE RUPEE" },
  { code: "LKR", name: "SRI LANKAN RUPEE" },
  { code: "MYR", name: "MALAYSIAN RINGGIT" },
  { code: "DKK", name: "DANISH KRONE" },
  { code: "SCR", name: "SEYCHELLES RUPEE" },
  { code: "BHD", name: "BAHRAINI DINAR" },
  { code: "GHS", name: "GHANAIAN CEDI" },
  { code: "BND", name: "BRUNEI DOLLAR" },
  { code: "TND", name: "TUNISIAN DINAR" },
  { code: "KRW", name: "SOUTH KOREAN WON" },
  { code: "SGD", name: "SINGAPORE DOLLAR" },
  { code: "TWD", name: "TAIWAN DOLLAR" },
  { code: "HKD", name: "HONG KONG DOLLAR" },
  { code: "JOD", name: "JORDANIAN DINAR" },
  { code: "IQD", name: "IRAQI DINAR" },
  { code: "TRL", name: "TURKISH LIRA" },
  { code: "QAR", name: "QATARI RIYAL" },
  { code: "THB", name: "THAILAND BAHT" },
];

// const mergedCurrencies = [
//   ...luluCurrencies,
//   ...fardanCurrencies,
//   ...ansariCurrencies,
// ];

// const deDuplicatedArray = new Map(
//   mergedCurrencies.map((item) => [item.code, item])
// ).values();

// const uniqueCurrencies = Array.from(deDuplicatedArray);
// uniqueCurrencies.sort((a, b) => a.name.localeCompare(b.name));
const getCommonCurrencies = (a, b, c) => {
  // Create a Set of currency codes from the first array
  const codesB = new Set(b.map((x) => x.code));
  const codesC = new Set(c.map((x) => x.code));

  // Filter the first array to include only currencies present in both other sets
  return a.filter(
    (currency) => codesB.has(currency.code) && codesC.has(currency.code)
  );
};

const commonCurrencies = getCommonCurrencies(
  luluCurrencies,
  fardanCurrencies,
  ansariCurrencies
);

// Sort alphabetically by currency name
commonCurrencies.sort((a, b) => a.name.localeCompare(b.name));

console.log(commonCurrencies);
export default commonCurrencies;
